"""empty message

Revision ID: 0883ca07bf29
Revises: ac047a7444ff
Create Date: 2024-07-07 13:48:39.456691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0883ca07bf29'
down_revision = 'ac047a7444ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'reception', ['id'])
    op.create_unique_constraint(None, 'stock', ['id'])
    op.create_unique_constraint(None, 'user_stock', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stock', type_='unique')
    op.drop_constraint(None, 'stock', type_='unique')
    op.drop_constraint(None, 'reception', type_='unique')
    # ### end Alembic commands ###
