"""empty message

Revision ID: 1a4b07c1cbb0
Revises: 73ff9662412b
Create Date: 2024-07-10 14:30:57.048089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4b07c1cbb0'
down_revision = '73ff9662412b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rack_level_slot_stock_id_fkey', 'rack_level_slot', type_='foreignkey')
    op.drop_column('rack_level_slot', 'stock_id')
    op.add_column('stock', sa.Column('rack_level_slot_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'stock', 'rack_level_slot', ['rack_level_slot_id'], ['id'], onupdate='cascade', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.drop_column('stock', 'rack_level_slot_id')
    op.add_column('rack_level_slot', sa.Column('stock_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('rack_level_slot_stock_id_fkey', 'rack_level_slot', 'stock', ['stock_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    # ### end Alembic commands ###
