"""empty message

Revision ID: 1eb5e00e6ea1
Revises: 
Create Date: 2024-05-31 18:02:52.965367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb5e00e6ea1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waiting_room',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('max_stocks', sa.Integer(), nullable=False),
    sa.Column('max_weight', sa.DECIMAL(), nullable=False),
    sa.Column('occupied_slots', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'issue', ['id'])
    op.create_unique_constraint(None, 'product', ['id'])
    op.create_unique_constraint(None, 'reception', ['id'])
    op.add_column('stock', sa.Column('waiting_room_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'stock', ['id'])
    op.create_foreign_key(None, 'stock', 'waiting_room', ['waiting_room_id'], ['id'], onupdate='cascade', ondelete='SET NULL')
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.drop_constraint(None, 'stock', type_='unique')
    op.drop_column('stock', 'waiting_room_id')
    op.drop_constraint(None, 'reception', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'issue', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_table('waiting_room')
    # ### end Alembic commands ###
