"""empty message

Revision ID: 1f2de58280a9
Revises: 5ddb35d84e8d
Create Date: 2024-07-04 09:58:04.695027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2de58280a9'
down_revision = '5ddb35d84e8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rack_level_slot',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rack_level_slot_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('rack_level_id', sa.String(), nullable=False),
    sa.Column('stock_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rack_level_id'], ['rack_level.id'], onupdate='SET NULL', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], onupdate='SET NULL', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rack_level_slot_id'), 'rack_level_slot', ['id'], unique=True)
    op.add_column('user_stock', sa.Column('to_rack_level_slot_id', sa.String(), nullable=True))
    op.add_column('user_stock', sa.Column('from_rack_level_slot_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'user_stock', 'rack_level_slot', ['from_rack_level_slot_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_stock', 'rack_level_slot', ['to_rack_level_slot_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stock', type_='foreignkey')
    op.drop_constraint(None, 'user_stock', type_='foreignkey')
    op.drop_column('user_stock', 'from_rack_level_slot_id')
    op.drop_column('user_stock', 'to_rack_level_slot_id')
    op.drop_index(op.f('ix_rack_level_slot_id'), table_name='rack_level_slot')
    op.drop_table('rack_level_slot')
    # ### end Alembic commands ###
