"""empty message

Revision ID: 2f0fc91806bd
Revises: 
Create Date: 2024-05-31 11:11:41.811701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f0fc91806bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('wholesale_price', sa.DECIMAL(), nullable=False),
    sa.Column('amount_in_goods', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('weight', sa.DECIMAL(), nullable=False),
    sa.Column('legacy_product', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=75), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('employment_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_staff', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_password_set', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_move_stocks', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_recept_stocks', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_issue_stocks', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('category_product_association_table',
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], onupdate='cascade', ondelete='cascade')
    )
    op.create_table('issue',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('reception',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reception_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('weight', sa.DECIMAL(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('reception_id', sa.String(), nullable=True),
    sa.Column('issue_id', sa.String(), nullable=True),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('is_issued', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reception_id'], ['reception.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    op.drop_table('reception')
    op.drop_table('issue')
    op.drop_table('category_product_association_table')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('category')
    # ### end Alembic commands ###
