"""empty message

Revision ID: 3265a076a62b
Revises: 540905fcd440
Create Date: 2024-07-15 11:23:31.183936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3265a076a62b'
down_revision = '540905fcd440'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
