"""empty message

Revision ID: 37bd3d8f84e4
Revises: b89806b6cb3c
Create Date: 2024-06-07 17:23:34.212008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37bd3d8f84e4'
down_revision = 'b89806b6cb3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
