"""empty message

Revision ID: 3c2fda2c2f50
Revises: 1345ad6bd5e9
Create Date: 2024-06-09 10:56:07.261669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2fda2c2f50'
down_revision = '1345ad6bd5e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'issue', ['id'])
    op.create_unique_constraint(None, 'product', ['id'])
    op.create_unique_constraint(None, 'reception', ['id'])
    op.create_unique_constraint(None, 'stock', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'user_stock', ['id'])
    op.drop_constraint('user_stock_stock_id_fkey', 'user_stock', type_='foreignkey')
    op.drop_constraint('user_stock_issue_id_fkey', 'user_stock', type_='foreignkey')
    op.drop_constraint('user_stock_from_waiting_room_id_fkey', 'user_stock', type_='foreignkey')
    op.drop_constraint('user_stock_to_waiting_room_id_fkey', 'user_stock', type_='foreignkey')
    op.drop_constraint('user_stock_user_id_fkey', 'user_stock', type_='foreignkey')
    op.create_foreign_key(None, 'user_stock', 'waiting_room', ['to_waiting_room_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_stock', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_stock', 'stock', ['stock_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_stock', 'issue', ['issue_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_stock', 'waiting_room', ['from_waiting_room_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(None, 'waiting_room', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'waiting_room', type_='unique')
    op.drop_constraint(None, 'user_stock', type_='foreignkey')
    op.drop_constraint(None, 'user_stock', type_='foreignkey')
    op.drop_constraint(None, 'user_stock', type_='foreignkey')
    op.drop_constraint(None, 'user_stock', type_='foreignkey')
    op.drop_constraint(None, 'user_stock', type_='foreignkey')
    op.create_foreign_key('user_stock_user_id_fkey', 'user_stock', 'user', ['user_id'], ['id'])
    op.create_foreign_key('user_stock_to_waiting_room_id_fkey', 'user_stock', 'waiting_room', ['to_waiting_room_id'], ['id'])
    op.create_foreign_key('user_stock_from_waiting_room_id_fkey', 'user_stock', 'waiting_room', ['from_waiting_room_id'], ['id'])
    op.create_foreign_key('user_stock_issue_id_fkey', 'user_stock', 'issue', ['issue_id'], ['id'])
    op.create_foreign_key('user_stock_stock_id_fkey', 'user_stock', 'stock', ['stock_id'], ['id'])
    op.drop_constraint(None, 'user_stock', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'stock', type_='unique')
    op.drop_constraint(None, 'reception', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'issue', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
