"""empty message

Revision ID: 434a53873de8
Revises: a7cee2435bf0
Create Date: 2024-06-06 08:39:20.265857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434a53873de8'
down_revision = 'a7cee2435bf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'issue', ['id'])
    op.create_unique_constraint(None, 'product', ['id'])
    op.create_unique_constraint(None, 'reception', ['id'])
    op.create_unique_constraint(None, 'stock', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'waiting_room', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'waiting_room', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'stock', type_='unique')
    op.drop_constraint(None, 'reception', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'issue', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
