"""empty message

Revision ID: 44fefb3ea0ff
Revises: 1a0dec957a48
Create Date: 2024-05-25 17:11:18.214017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44fefb3ea0ff'
down_revision = '1a0dec957a48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'issue', ['id'])
    op.create_unique_constraint(None, 'product', ['id'])
    op.add_column('reception', sa.Column('description', sa.String(length=400), nullable=True))
    op.create_unique_constraint(None, 'reception', ['id'])
    op.create_unique_constraint(None, 'stock', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'stock', type_='unique')
    op.drop_constraint(None, 'reception', type_='unique')
    op.drop_column('reception', 'description')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'issue', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
