"""empty message

Revision ID: 529398fa26eb
Revises: fd41c1256e78
Create Date: 2024-06-14 09:10:40.933286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529398fa26eb'
down_revision = 'fd41c1256e78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
