"""empty message

Revision ID: 557187556bea
Revises: 580c3be292be
Create Date: 2024-06-16 10:32:32.633620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557187556bea'
down_revision = '580c3be292be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
