"""empty message

Revision ID: 580c3be292be
Revises: cf9b0ab9f860
Create Date: 2024-06-14 14:31:20.479921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580c3be292be'
down_revision = 'cf9b0ab9f860'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('occupied_weight', sa.Integer(), nullable=False))
    op.add_column('section', sa.Column('occupied_racks', sa.Integer(), nullable=False))
    op.drop_constraint('section_warehouse_id_fkey', 'section', type_='foreignkey')
    op.create_foreign_key(None, 'section', 'warehouse', ['warehouse_id'], ['id'], onupdate='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'section', type_='foreignkey')
    op.create_foreign_key('section_warehouse_id_fkey', 'section', 'warehouse', ['warehouse_id'], ['id'], onupdate='CASCADE')
    op.drop_column('section', 'occupied_racks')
    op.drop_column('section', 'occupied_weight')
    # ### end Alembic commands ###
