"""empty message

Revision ID: 6a9f69006912
Revises: 1559468596fe
Create Date: 2024-09-24 20:37:51.366279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9f69006912'
down_revision = '1559468596fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'reception', ['id'])
    op.create_unique_constraint(None, 'stock', ['id'])
    op.add_column('user_stock', sa.Column('reception_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user_stock', ['id'])
    op.create_foreign_key(None, 'user_stock', 'reception', ['reception_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stock', type_='foreignkey')
    op.drop_constraint(None, 'user_stock', type_='unique')
    op.drop_column('user_stock', 'reception_id')
    op.drop_constraint(None, 'stock', type_='unique')
    op.drop_constraint(None, 'reception', type_='unique')
    # ### end Alembic commands ###
