"""empty message

Revision ID: 7fcb3df52ab0
Revises: 1eb5e00e6ea1
Create Date: 2024-05-31 18:34:53.684297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fcb3df52ab0'
down_revision = '1eb5e00e6ea1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waiting_room', sa.Column('current_stock_weight', sa.DECIMAL(), nullable=False))
    op.create_unique_constraint(None, 'waiting_room', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'waiting_room', type_='unique')
    op.drop_column('waiting_room', 'current_stock_weight')
    # ### end Alembic commands ###
