"""empty message

Revision ID: 80d81b249bf0
Revises: 1a4b07c1cbb0
Create Date: 2024-07-10 17:39:30.514661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d81b249bf0'
down_revision = '1a4b07c1cbb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
