"""empty message

Revision ID: 8163d8f5cdc5
Revises: 8e000ec0fc63
Create Date: 2024-05-21 18:06:51.418434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8163d8f5cdc5'
down_revision = '8e000ec0fc63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
