"""empty message

Revision ID: 9b668ff1e644
Revises: 0883ca07bf29
Create Date: 2024-07-07 13:54:10.158134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b668ff1e644'
down_revision = '0883ca07bf29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
