"""empty message

Revision ID: a8a1f1cd65d0
Revises: 4035dcdc178a
Create Date: 2024-05-21 18:56:54.940750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a1f1cd65d0'
down_revision = '4035dcdc178a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
