"""empty message

Revision ID: a8e10589ea18
Revises: 52d925bdf4aa
Create Date: 2024-07-11 09:50:35.573164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8e10589ea18'
down_revision = '52d925bdf4aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'reception', ['id'])
    op.create_unique_constraint(None, 'stock', ['id'])
    op.alter_column('user_stock', 'moved_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_unique_constraint(None, 'user_stock', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stock', type_='unique')
    op.alter_column('user_stock', 'moved_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'stock', type_='unique')
    op.drop_constraint(None, 'reception', type_='unique')
    # ### end Alembic commands ###
