"""empty message

Revision ID: ab4aa4c79d99
Revises: 557187556bea
Create Date: 2024-06-16 10:34:43.733020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4aa4c79d99'
down_revision = '557187556bea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rack',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rack_name', sa.String(length=400), nullable=False),
    sa.Column('max_weight', sa.DECIMAL(), nullable=False),
    sa.Column('available_weight', sa.DECIMAL(), nullable=False),
    sa.Column('occupied_weight', sa.Integer(), nullable=False),
    sa.Column('max_levels', sa.Integer(), nullable=False),
    sa.Column('available_levels', sa.DECIMAL(), nullable=False),
    sa.Column('occupied_levels', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], onupdate='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rack_id'), 'rack', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rack_id'), table_name='rack')
    op.drop_table('rack')
    # ### end Alembic commands ###
