"""empty message

Revision ID: b89806b6cb3c
Revises: c3bc78cfb5ca
Create Date: 2024-06-07 17:04:02.287620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b89806b6cb3c'
down_revision = 'c3bc78cfb5ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stock_id', sa.String(), nullable=False),
    sa.Column('moved_at', sa.DateTime(), nullable=False),
    sa.Column('from_waiting_room_id', sa.String(), nullable=True),
    sa.Column('to_waiting_room_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['from_waiting_room_id'], ['waiting_room.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.ForeignKeyConstraint(['to_waiting_room_id'], ['waiting_room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_stocks_association_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stocks_association_table',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stock_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('moved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('from_waiting_room_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('to_waiting_room_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_waiting_room_id'], ['waiting_room.id'], name='user_stocks_association_table_from_waiting_room_id_fkey'),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name='user_stocks_association_table_id_fkey'),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], name='user_stocks_association_table_stock_id_fkey'),
    sa.ForeignKeyConstraint(['to_waiting_room_id'], ['waiting_room.id'], name='user_stocks_association_table_to_waiting_room_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_stocks_association_table_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'user_id', 'stock_id', name='user_stocks_association_table_pkey')
    )
    op.drop_table('user_stock')
    # ### end Alembic commands ###
