"""empty message

Revision ID: c3bc78cfb5ca
Revises: 434a53873de8
Create Date: 2024-06-07 15:08:02.170109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3bc78cfb5ca'
down_revision = '434a53873de8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stocks_association_table',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stock_id', sa.String(), nullable=False),
    sa.Column('moved_at', sa.DateTime(), nullable=False),
    sa.Column('from_waiting_room_id', sa.String(), nullable=True),
    sa.Column('to_waiting_room_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['from_waiting_room_id'], ['waiting_room.id'], ),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.ForeignKeyConstraint(['to_waiting_room_id'], ['waiting_room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'stock_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stocks_association_table')
    # ### end Alembic commands ###
