"""empty message

Revision ID: ceadf1cf5b61
Revises: 309e033dbbab
Create Date: 2024-06-26 08:47:14.142406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceadf1cf5b61'
down_revision = '309e033dbbab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'reception', ['id'])
    op.add_column('section', sa.Column('reserved_weight', sa.DECIMAL(), nullable=False))
    op.add_column('section', sa.Column('weight_to_reserve', sa.DECIMAL(), nullable=False))
    op.create_unique_constraint(None, 'stock', ['id'])
    op.create_unique_constraint(None, 'user_stock', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stock', type_='unique')
    op.drop_constraint(None, 'stock', type_='unique')
    op.drop_column('section', 'weight_to_reserve')
    op.drop_column('section', 'reserved_weight')
    op.drop_constraint(None, 'reception', type_='unique')
    # ### end Alembic commands ###
