"""empty message

Revision ID: cf9b0ab9f860
Revises: 529398fa26eb
Create Date: 2024-06-14 13:01:10.778128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9b0ab9f860'
down_revision = '529398fa26eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse', sa.Column('occupied_sections', sa.Integer(), nullable=False))
    op.add_column('warehouse', sa.Column('occupied_waiting_rooms', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouse', 'occupied_waiting_rooms')
    op.drop_column('warehouse', 'occupied_sections')
    # ### end Alembic commands ###
