"""empty message

Revision ID: d223a3f42c02
Revises: 44fefb3ea0ff
Create Date: 2024-05-27 15:15:01.198050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd223a3f42c02'
down_revision = '44fefb3ea0ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('description', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue', 'description')
    # ### end Alembic commands ###
